[package]
name = "simple-eigentrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
ndarray = "0.15.6"
ndarray-linalg = "0.16.0"
